language: python
python:
  - "2.7"
sudo: false
services:
  - redis-server
addons:
  apt:
    packages:
    - python-argparse
    - python-lxml
    - python-mysqldb
    - python-yaml
    - python-redis
    - python-tz
    # These packages do not work correctly in the Travis CI Docker VMs:
    # - python-zmq
    # - python-mysqldb
virtualenv:
  system_site_packages: true
install:
  # Install via pip because these packages have problems in Travis CI Docker images:
  - pip install pyzmq
  - pip install MySQL-python
  # Always install via pip:
  - pip install isodate
  - pip install bottle
  - pip install coveralls
  - pip install scrutinizer-ocular
before_script:
  - cp tests/testdata/serviceinfo-unittest.travis.yaml config/serviceinfo-unittest.yaml
  - mysql -e 'create database rdt_iff_test;'
  - mysql -u travis rdt_iff_test < tests/testdata/iff-testset.sql
script: coverage run --source serviceinfo -m py.test
after_success:
  - coveralls
  - ocular --data-file ".coverage"
notifications:
  webhooks:
    # trigger Buildtime Trend Service to parse Travis CI log
    - https://buildtimetrend.herokuapp.com/travis
